enum ESCT_ESupportType
{
	UNDEFINED = -1,
	QRF = 0,
	QRF_VEHICLE = 2,
//	SPECOPS = 4,
//	HELI_STRIKE = 8,
//	HELI_LOITER = 16,
//	MORTAR_HE = 32,
//	MORTAR_SMOKE = 64,
//	MORTAR_FLARE = 128,
//	ARTILLERY = 256
}
